version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: gym-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  gym-app:
    build: .
    container_name: gym-fullstack-app
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - ASPNETCORE_URLS=http://+:8080
      - WebApplicationUrl=http://localhost:8080
      - MongoDB__ConnectionString=mongodb://mongodb:27017/
      - MongoDB__DatabaseName=gym-db
      - Jwt__Secret=${JWT_SECRET}
      - Tg__Bot__Token=${TG_BOT_TOKEN}
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: