version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: gym-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=my-test-db
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  gym-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-fullstack-app
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - MongodDb__ConnectionString=mongodb://mongodb:27017/  # <-- используем имя сервиса
    depends_on:
      - mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data: