server {
    listen 80;
    server_name gym-buddy.ru localhost;
    # Редирект всего HTTP трафика на HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name gym-buddy.ru;

    # SSL настройки
    ssl_certificate /etc/nginx/certs/gym-buddy.ru_cert.pem;
    ssl_certificate_key /etc/nginx/certs/gym-buddy.ru_private_key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Общие заголовки для всех проксируемых запросов
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;

    # 1. UI (Blazor WebAssembly - статика)
    location / {
        proxy_pass http://ui:80;
    }

    # 2. Backend (WebApi)
    location /api/ {
        proxy_pass http://backend:8080/api/;
    }

    # 3. BFF (Backend For Frontend)
    # Слеэш в конце proxy_pass "обрезает" префикс /bff/ при передаче в контейнер
    location /bff/ {
        proxy_pass http://gym-bff:8080/;
        # КРИТИЧНО: Говорим ASP.NET Core, что снаружи он висит на пути /bff
        proxy_set_header X-Forwarded-Prefix /bff;
    }

    # 4. Authorization Server (OpenID Connect)
    location /auth/ {
        proxy_pass http://gym-authserver:8080/;
        proxy_set_header X-Forwarded-Prefix /auth;
    }

    # 5. Authorization Server Admin API
    location /auth-admin/ {
        proxy_pass http://gym-authadmin:8080/;
        proxy_set_header X-Forwarded-Prefix /auth-admin;
    }
}