
#user  nobody;
worker_processes  2;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

http {

    server {
    	listen 80;
    	server_name localhost;
    	return 301 https://$host$request_uri;
    }
    
    server {

	    listen 443 ssl;

	    #ssl_certificate;
            #ssl_certificate_key;
    
            ssl_protocols TLSv1.2 TLSv1.3;

	    location / {
            proxy_pass https://localhost:7092;
	    }

	    location /bff/ {
            proxy_pass https://localhost:7222/;
	    }

	    location /auth-server/ {
            proxy_pass https://localhost:7218/;
	        proxy_redirect /Login /auth-server/Login;
	        proxy_redirect /Approve /auth-server/Approve;
	        proxy_redirect /Error /auth-server/Error;
	    }

	    location /auth-server-admin/ {
            proxy_pass https://localhost:7193/;
	    }

	    location /services/ {
            proxy_pass https://localhost:7246/;
	    }
	
    }
}
