<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gym.AuthorizationServer.Infrastructure\Gym.AuthorizationServer.Infrastructure.csproj" />
    <ProjectReference Include="..\Gym.RabbitMQ.Topology\Gym.RabbitMQ.Topology.csproj" />
  </ItemGroup>

</Project>
